services:
  - type: web
    name: car-note-pdf-api
    env: node
    region: singapore  # Tokyo がないため最も近い
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
